[build]
  publish = "public"
  command = "echo 'no build step'"

[functions]
  directory    = "netlify/functions"
  node_bundler = "nft"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200

[dev]
  command     = "bun --hot src/index.ts"
  port        = 3000
  targetPort  = 3000
  autoLaunch  = false
